// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chat_appAPI.models;

namespace chat_appAPI.Migrations
{
    [DbContext(typeof(ChatDBContext))]
    [Migration("20190930131535_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("chat_appAPI.models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(355)")
                        .HasMaxLength(355);

                    b.Property<bool>("HasTitle")
                        .HasColumnType("bit");

                    b.Property<int>("RecId")
                        .HasColumnType("int");

                    b.Property<int?>("RecUserId")
                        .HasColumnType("int");

                    b.Property<int>("SendId")
                        .HasColumnType("int");

                    b.Property<int?>("SendUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("RecUserId");

                    b.HasIndex("SendUserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("chat_appAPI.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("chat_appAPI.models.Message", b =>
                {
                    b.HasOne("chat_appAPI.models.User", "RecUser")
                        .WithMany()
                        .HasForeignKey("RecUserId");

                    b.HasOne("chat_appAPI.models.User", "SendUser")
                        .WithMany()
                        .HasForeignKey("SendUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
